### ISSUE TITLE
aaa

### ISSUE THREAD

**Issue by ashstarry** [ashstarry/cloud_computing-labs#10]
https://github.com/aws/aws-app-mesh-roadmap/issues/236

**Comment by ysdongAmazon** [comment]
https://github.com/aws/aws-app-mesh-examples/tree/main/walkthroughs/howto-external-traffic

**Comment by ashstarry** [comment]
https://github.com/aws/aws-app-mesh-roadmap/issues/138

**Comment by ashstarry** [comment]
https://github.com/aws/aws-app-mesh-roadmap/issues/138

**Comment by ashstarry** [comment]
```
https://github.com/aws/aws-app-mesh-roadmap/issues/138
```

**Comment by ashstarry** [comment]
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
      annotations:
        appmesh.k8s.aws/egressIgnoredPorts: "443"
    spec:
      containers:
      - name: my-container
        image: my-image

```
