### ISSUE TITLE
aaa

### ISSUE THREAD

**Issue by ashstarry** [ashstarry/cloud_computing-labs#2]
AWS App Mesh Controller for Kubernetes treats certain updates as requiring a replacement of the resource rather than an in-place update

The lifecycle block in a Terraform resource configuration allows you to control how Terraform manages the resource throughout its lifecycle. One of the configuration options in a lifecycle block is `ignore_changes`. 

The `ignore_changes` attribute is used to prevent Terraform from considering certain changes to the resource as needing a new resource. This means that if these attributes change, Terraform will not attempt to recreate the resource. It will treat it as if there was no change to the resource.

This can be helpful in situations where certain changes to a resource would normally force a new resource to be created, but where the creation of a new resource is not desirable or necessary. 

For example, in your situation, you are experiencing issues where changes to the `perRetryTimeout.value` field are causing Terraform to try and recreate the VirtualRouter. By using a lifecycle block with `ignore_changes` set to ignore this field, Terraform will not attempt to recreate the VirtualRouter when only this field changes.

Here's what that would look like in your Terraform configuration:

```hcl
resource "kubernetes_manifest" "virtualrouter" {
  manifest = { ... }

  lifecycle {
    ignore_changes = [
      manifest.spec.routes[0].httpRoute.retryPolicy.perRetryTimeout.value,
      # Add other attributes as necessary.
    ]
  }
}
```

In this configuration, if the `perRetryTimeout.value` changes, Terraform will not try to recreate the VirtualRouter. 

Please note that using `ignore_changes` may have side effects, depending on what attributes you're ignoring. If these attributes have an impact on the functioning of the resource and you're ignoring changes to them, the actual state of the resource might not reflect the state described in your Terraform configuration. So use this feature with caution and make sure to thoroughly test your setup to ensure it behaves as expected.

**Comment by ashstarry** [comment]
The requirement for the prefix in a GatewayRoute to both start and end with a slash ("/") is an enforced convention in the AWS App Mesh Kubernetes Controller to maintain consistency and prevent ambiguity when defining the paths to be matched in your routes.

Here's a brief explanation and some examples to illustrate:

Consider two routes, one with prefix /product and another with prefix /product-special. If a request comes in with path /product-special/1234, both routes will match the request, because both prefixes are present in the path. This creates ambiguity about which route should process the request.

Now consider if the enforced convention is applied and routes are defined with prefixes /product/ and /product-special/. With this convention, a request with path /product-special/1234 would only match the second route, eliminating the ambiguity.

In essence, the convention is put in place to ensure that your routes are more specific and don't unintentionally overlap, causing confusion or misrouting.

Remember, this convention is specific to the AWS App Mesh Controller for Kubernetes and may not apply or be required in other contexts or with different routing mechanisms. This is why it's always important to refer to the documentation or other authoritative resources for the specific tool or service you are using.

**Comment by ashstarry** [comment]
The error message `BadRequestException: Route must define a port match criteria if the Virtual Router has multiple listeners.` is indicating that if a VirtualRouter has multiple listeners defined, each Route in the router must specify a port match. 

In your configuration, the VirtualRouter has two listeners, one for gRPC on port 63001 and one for HTTP on port 64001. However, in your `conor-grpc` route, although you have specified a `port` in the `match` field, it's not under the appropriate parent field according to the AWS App Mesh API specification. 

The `port` field should be under `match.metadata` for gRPC routes, as follows:

```yaml
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  namespace: mesh
  name: conor
spec:
  listeners:
    - portMapping:
        port: 63001
        protocol: grpc
    - portMapping:
        port: 64001
        protocol: http
  routes:
    - name: conor-grpc
      priority: 2
      grpcRoute:
        action:
          weightedTargets:
            - virtualNodeRef:
                name: conor
              weight: 100
              port: 63001
        match:
          serviceName: srv.conor.Conor
          metadata:
            - name: ":authority"
              match:
                range:
                  start: 0
                  end: 63001
```

In this configuration, the `:authority` pseudo-header is used to specify the port, which aligns with the HTTP/2 specification that gRPC is based on. This ensures that the router can correctly distinguish between requests that should go to the gRPC service versus the HTTP service.

Please adjust the values according to your application requirements, and make sure to validate the configuration with your use case.
